#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-zkclient
Version  : 0.10
Release  : 1
URL      : https://github.com/sgroschupf/zkclient/archive/0.10.tar.gz
Source0  : https://github.com/sgroschupf/zkclient/archive/0.10.tar.gz
Source1  : https://repo1.maven.org/maven2/com/101tec/zkclient/0.10/zkclient-0.10.jar
Source2  : https://repo1.maven.org/maven2/com/101tec/zkclient/0.10/zkclient-0.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-zkclient-data = %{version}-%{release}

%description
ZkClient: a zookeeper client, that makes life a little easier.
=====
+ Website: 			https://github.com/sgroschupf/zkclient
+ Apache 2.0 License

%package data
Summary: data components for the mvn-zkclient package.
Group: Data

%description data
data components for the mvn-zkclient package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/101tec/zkclient/0.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/101tec/zkclient/0.10/zkclient-0.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/101tec/zkclient/0.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/101tec/zkclient/0.10/zkclient-0.10.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/101tec/zkclient/0.10/zkclient-0.10.jar
/usr/share/java/.m2/repository/com/101tec/zkclient/0.10/zkclient-0.10.pom
